# Generated by Django 5.2.7 on 2026-02-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postengagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
